import fs from 'fs/promises';
import path from 'path';
import type {
  GeneratedDocs,
  LumikoConfig,
  ContextBundle,
  ContextManifest,
  DependencyGraph,
} from '../types/index.js';

// Lumiko version is baked into the manifest so agents can tell when a bundle
// was generated by an older version of the generator.
const LUMIKO_VERSION = '1.0.0';

export interface WriteOptions {
  /** Pre-built dep graph. Written alongside the .context/ bundle when present. */
  graph?: DependencyGraph | null;
}

export async function writeOutput(
  docs: GeneratedDocs,
  projectPath: string,
  config: LumikoConfig,
  options: WriteOptions = {},
): Promise<void> {
  const writes: Promise<void>[] = [];

  // ── Markdown docs → config.output.directory (default: docs/) ──────────
  if (
    (config.docs.readme && docs.readme) ||
    (config.docs.architecture && docs.architecture) ||
    (config.docs.api && docs.api)
  ) {
    const outputDir = path.join(projectPath, config.output.directory);
    await fs.mkdir(outputDir, { recursive: true });

    if (config.docs.readme && docs.readme) {
      writes.push(fs.writeFile(path.join(outputDir, 'README.md'), docs.readme + '\n'));
    }
    if (config.docs.architecture && docs.architecture) {
      writes.push(fs.writeFile(path.join(outputDir, 'architecture.md'), docs.architecture + '\n'));
    }
    if (config.docs.api && docs.api) {
      writes.push(fs.writeFile(path.join(outputDir, 'api.md'), docs.api + '\n'));
    }
  }

  // ── .context/ bundle → config.output.contextDirectory (default: .context/) ──
  if (config.output.formats.includes('context') && docs.context && docs.context.entries.length > 0) {
    await writeContextBundle(docs.context, projectPath, config, options.graph ?? null);
  } else if (config.output.formats.includes('context') && options.graph) {
    // Bundle failed or was skipped, but we still want the graph on disk.
    const contextDir = path.join(projectPath, config.output.contextDirectory);
    await fs.mkdir(contextDir, { recursive: true });
    await fs.writeFile(
      path.join(contextDir, 'graph.json'),
      JSON.stringify(options.graph, null, 2) + '\n',
    );
  }

  await Promise.all(writes);
}

/**
 * Write a context bundle to disk, creating subdirectories as needed.
 * Generates a manifest.json locally (not from Claude) as the bundle index.
 * If a dep graph is provided, writes it alongside and includes it in the manifest.
 */
async function writeContextBundle(
  bundle: ContextBundle,
  projectPath: string,
  config: LumikoConfig,
  graph: DependencyGraph | null,
): Promise<void> {
  const contextDir = path.join(projectPath, config.output.contextDirectory);
  await fs.mkdir(contextDir, { recursive: true });

  // Write each entry from Claude
  await Promise.all(
    bundle.entries.map(async (entry) => {
      const fullPath = path.join(contextDir, entry.path);
      await fs.mkdir(path.dirname(fullPath), { recursive: true });

      const serialized =
        entry.kind === 'json'
          ? JSON.stringify(entry.content, null, 2) + '\n'
          : String(entry.content).trimEnd() + '\n';

      await fs.writeFile(fullPath, serialized);
    }),
  );

  // Write the dep graph (local, no Claude)
  if (graph) {
    await fs.writeFile(
      path.join(contextDir, 'graph.json'),
      JSON.stringify(graph, null, 2) + '\n',
    );
  }

  // Generate manifest.json locally (source of truth for what's in the bundle)
  const manifest = buildManifest(bundle, config, graph);
  await fs.writeFile(
    path.join(contextDir, 'manifest.json'),
    JSON.stringify(manifest, null, 2) + '\n',
  );

  // Write a lightweight README inside .context/ so humans who stumble into it
  // understand what this is.
  const readme = buildContextReadme(config.project.name);
  await fs.writeFile(path.join(contextDir, 'README.md'), readme);
}

/**
 * Build the manifest.json for a bundle. The manifest is generated locally so
 * Lumiko controls its schema and version rather than relying on Claude.
 */
function buildManifest(
  bundle: ContextBundle,
  config: LumikoConfig,
  graph: DependencyGraph | null,
): ContextManifest {
  // Best-effort extraction of project summary from overview.json if present.
  const overview = bundle.entries.find(
    (e) => e.path === 'overview.json' && e.kind === 'json',
  );
  const summary =
    overview && typeof overview.content === 'object' && overview.content !== null
      ? ((overview.content as Record<string, unknown>).summary as string | undefined) ??
        config.project.description ??
        ''
      : config.project.description ?? '';

  const files = bundle.entries.map((e) => ({
    path: e.path,
    description: describeEntry(e.path),
  }));

  if (graph) {
    files.push({
      path: 'graph.json',
      description: describeEntry('graph.json'),
    });
  }

  return {
    lumiko: {
      version: LUMIKO_VERSION,
      generatedAt: new Date().toISOString(),
      model: config.claude.model,
    },
    project: {
      name: config.project.name,
      summary,
    },
    files,
  };
}

function describeEntry(entryPath: string): string {
  if (entryPath === 'overview.json') return 'Project overview — name, stack, purpose, entry points';
  if (entryPath === 'architecture.json') return 'System design — patterns, layers, modules, data flow';
  if (entryPath === 'conventions.md') return 'Coding conventions and patterns';
  if (entryPath === 'commands.json') return 'Build, test, and dev commands + env vars';
  if (entryPath === 'graph.json') return 'Import/dependency graph — nodes, edges, orphans, hotspots';
  if (entryPath.startsWith('modules/')) {
    const name = entryPath.replace(/^modules\//, '').replace(/\.json$/, '');
    return `Per-file details for module "${name.replace(/-/g, '/')}"`;
  }
  return 'Context file';
}

function buildContextReadme(projectName: string): string {
  return `# .context/

This directory is a machine-readable context bundle for **${projectName}**,
generated by [Lumiko](https://github.com/mirako-dev/lumiko).

It's designed to be loaded by AI coding agents (Claude Code, Cursor, Copilot,
custom RAG pipelines) so they can understand this codebase without having to
re-read every source file.

## Layout

- \`manifest.json\` — index of all files in this bundle
- \`overview.json\` — project summary, stack, entry points
- \`architecture.json\` — system design, modules, data flow
- \`conventions.md\` — coding conventions
- \`commands.json\` — build, test, dev commands + env vars
- \`modules/\` — one file per directory with per-file details

## Regenerating

Run \`lumiko generate\` from the project root to refresh this bundle.
`;
}

// ── Output stats ────────────────────────────────────────────────────────

export interface FileStat {
  name: string;
  size: string;
}

export async function getOutputStats(
  projectPath: string,
  config: LumikoConfig,
): Promise<FileStat[]> {
  const stats: FileStat[] = [];

  // Markdown docs
  const outputDir = path.join(projectPath, config.output.directory);
  for (const name of ['README.md', 'architecture.md', 'api.md']) {
    const filePath = path.join(outputDir, name);
    try {
      const stat = await fs.stat(filePath);
      stats.push({ name: `${config.output.directory}/${name}`, size: formatBytes(stat.size) });
    } catch {
      // File doesn't exist, skip
    }
  }

  // Context bundle — walk the directory and list every file
  if (config.output.formats.includes('context')) {
    const contextDir = path.join(projectPath, config.output.contextDirectory);
    try {
      const bundleFiles = await walkDir(contextDir);
      for (const file of bundleFiles) {
        const rel = path.relative(projectPath, file).replace(/\\/g, '/');
        const stat = await fs.stat(file);
        stats.push({ name: rel, size: formatBytes(stat.size) });
      }
    } catch {
      // Directory doesn't exist, skip
    }
  }

  return stats;
}

/** Recursively list all files under a directory. */
async function walkDir(dir: string): Promise<string[]> {
  const results: string[] = [];
  const entries = await fs.readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...(await walkDir(fullPath)));
    } else if (entry.isFile()) {
      results.push(fullPath);
    }
  }

  return results;
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
  return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
}
